### ISSUE TITLE
Link is dead - 404

### ISSUE THREAD

**Issue by r4inX** [itechpros/servoy-war-builder#1]
https://github.com/itechpros/servoy-war-builder/blob/df08946991762953b2dc5947e2106605627cb3b2/README.md?plain=1#L140C130-L140C130

The link to the supported servoy-versions is dead, returns a 404. 
Maybe i´m just blind but i cant find the list for the supported servoy-versions.

-Rain

**Comment by pbromwelljr** [comment]
Hey Rain!

Sorry about that. Seems we're having some permissions issues with that package listing. I've copied the available versions into the README at the bottom and updated the link. Let me know if you have any other questions/comments/concerns.

Thanks!

Paul
